// Admin Constants
export const GET_ALL_USER_REQUEST = "GET_ALL_USER_REQUEST";
export const GET_ALL_USER_SUCCESS = "GET_ALL_USER_SUCCESS";
export const GET_ALL_USER_FAIL = "GET_ALL_USER_FAIL";


// Gym Owner Constants
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";   
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";

export const VERIFY_REQUEST = "VERIFY_REQUEST";
export const VERIFY_SUCCESS = "VERIFY_SUCCESS";
export const VERIFY_FAIL = "VERIFY_FAIL";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

export const GET_LOGIN_USER_REQUEST = "GET_LOGIN_USER_REQUEST";
export const GET_LOGIN_USER_SUCCESS = "GET_LOGIN_USER_SUCCESS";
export const GET_LOGIN_USER_FAIL = "GET_LOGIN_USER_FAIL";

export const GET_ALL_TRAINERS_REQUEST = "GET_ALL_TRAINERS_REQUEST";
export const GET_ALL_TRAINERS_SUCCESS = "GET_ALL_TRAINERS_SUCCESS";
export const GET_ALL_TRAINERS_FAIL = "GET_ALL_TRAINERS_FAIL";

export const GET_ALL_TRAINEE_REQUEST = "GET_ALL_TRAINEE_REQUEST";
export const GET_ALL_TRAINEE_SUCCESS = "GET_ALL_TRAINEE_SUCCESS";
export const GET_ALL_TRAINEE_FAIL = "GET_ALL_TRAINEE_FAIL"; 

export const CLEAR_ERRORS = "CLEAR_ERRORS";